version: "3"
services:
  syncserver:
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION}
    image: syncstorage-rs:${VERSION}
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    ports:
      - "${EXTERNAL_PORT}:8000"
    environment:
      LOGLEVEL: warn
      SYNC_URL: ${SYNC_URL}:${PROXY_PORT}
      SYNC_CAPACITY: ${SYNC_CAPACITY}
      SYNC_MASTER_SECRET: ${SYNC_MASTER_SECRET}
      METRICS_HASH_SECRET: ${METRICS_HASH_SECRET}
      SYNC_SYNCSTORAGE_DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASS}@${DATABASE_SERVER}:${DATABASE_PORT}/${DATABASE_SYNC}
      SYNC_TOKENSERVER_DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASS}@${DATABASE_SERVER}:${DATABASE_PORT}/${DATABASE_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/__heartbeat__"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - mariadb
      
networks:
  mariadb:
    external: true